<a href="https://colab.research.google.com/github/khan085796-collab/Aftab_edurkon_2026-DS/blob/main/Project_9_Numpy_Assignment(1_50).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### === NumPy Retail Analytics Assignment ===

### == Part 1: Dataset Creation ==


In [ ]:

import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


### === Part 2: Basic Array Understanding ===

Question 1: Array Dimensions
The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

--Number of dimensions in sales_data

--Shape of sales_data

--Total number of values

--Data type of the array

--Memory occupied by the array

In [ ]:
### 1. Number of dimensions in sales_data

print(sales_data.ndim)

2


In [ ]:
### 2. Shape of sales_data

print(sales_data.shape)

(5, 6)


In [ ]:
### 3. Total number of values

print(sales_data.size)

30


In [ ]:
### 4. Data type of the array

print(sales_data.dtype)

int64


In [ ]:
### 5. Memory occupied by the array

print(sales_data.nbytes)

240


## --- Question 2: Store and Category Count ---

In [ ]:
### Total number of stores

print(len(stores))

5


In [ ]:
## Total number of product categories

print(len(categories))

6


In [ ]:
### Total number of store-category combinations

print(sales_data.size)

30


## --- Question 3: Sales Data Type Conversion ---

In [ ]:
# Convert sales_data into:

# float32
# float64
# Compare the memory used by both arrays.

# convert sales_data into float32
sales_float32 = sales_data.astype(np.float32)

# convert sales_data into float64
sales_float64 = sales_data.astype(np.float64)

## Display memory usage

print("Memory used by float32:", sales_float32.nbytes, "bytes")
print("Memory used by float64:", sales_float64.nbytes, "bytes")

Memory used by float32: 120 bytes
Memory used by float64: 240 bytes


## --- Part 3: Indexing and Data Extraction ---

## -- Question 4: Bengaluru Store Analysis --

In [ ]:

# Extract and display the complete sales row for Bengaluru.

bengaluru_sales = sales_data[0]
print("Bengaluru Sales:")
print(bengaluru_sales)


Bengaluru Sales:
[850000 420000 310000 275000 190000 225000]


## -- Question 5: Mumbai Cost Analysis --

In [ ]:
#Extract the total cost incurred by the Mumbai store for all product categories.

mumbai_cost = cost_data[3]
print("Mumbai Cost:")
print(mumbai_cost)

Mumbai Cost:
[790000 390000 265000 250000 165000 205000]


## -- Question 6: Electronics Sales Across Stores --

In [ ]:
# Extract the Electronics sales column from sales_data.

electronics_sales = sales_data[:, 0] ## : selects all stores( all rows)

print("Electronics Sales:")
print(electronics_sales)

Electronics Sales:
[ 850000  780000  920000 1050000  690000]


## --- Question 7: Clothing Cost Across Stores ---

In [ ]:
# Extract the Clothing cost for every store from cost_data.

# Extract Clothing cost for every store
clothing_cost = cost_data[:, 2]

print("Clothing Cost:")
print(clothing_cost)

Clothing Cost:
[220000 210000 245000 265000 205000]


## --- Question 8: Hyderabad Furniture Performance ---

In [ ]:
# Find the following for Hyderabad:

# Furniture sales
# Furniture cost
# Furniture profit

# Hyderabad Furniture sales
furniture_sales = sales_data[1, 3]

# Hyderabad Furniture cost
furniture_cost = cost_data[1, 3]

# Hyderabad Furniture profit
furniture_profit = furniture_sales - furniture_cost

print("Furniture Sales:", furniture_sales)
print("Furniture Cost:", furniture_cost)
print("Furniture Profit:", furniture_profit)

Furniture Sales: 310000
Furniture Cost: 225000
Furniture Profit: 85000


## --- Question 9: Chennai Category Range ---


In [ ]:
## Extract Chennai’s sales for the following categories:

# Groceries
# Clothing
# Furniture
# Use array slicing.

# Extract
chennai_sales = sales_data[2, 1:4]

print("Chennai Sales:")
print(chennai_sales)

Chennai Sales:
[390000 340000 260000]


## --- Question 10: Selected Store Analysis ---

In [ ]:
## --- Question 10: Selected Store Analysis ---
# Store indexes and category indexes

store_indexes = [0, 2, 4]
category_indexes = [0, 2, 4]

# Extract selected sales data using advanced indexing
selected_sales = sales_data[np.ix_(store_indexes, category_indexes)]

print("Selected Sales Data:")
print(selected_sales)


Selected Sales Data:
[[850000 310000 190000]
 [920000 340000 185000]
 [690000 280000 175000]]


## --- Part 4: Sales Aggregation ---

## -- Question 11: Company-Wide Sales --

In [ ]:
# Calculate the total sales revenue generated by all stores and all categories.

total_sales = np.sum(sales_data)

print("Total Sales Revenue:", total_sales)

Total Sales Revenue: 11675000


## -- Question 12: Store-Wise Sales --

In [ ]:
# Calculate total sales revenue for each store.

# Display the result together with the store names.

# Expected output format:

# Bengaluru: total sales
# Hyderabad: total sales
# Chennai: total sales
# Mumbai: total sales
# Pune: total sales

# Calculate total sales revenue for each store
store_total_sales = np.sum(sales_data, axis=1)

# Display store names with total sales
for store, total in zip(stores, store_total_sales):
    print(store + ":", total)

Bengaluru: 2270000
Hyderabad: 2295000
Chennai: 2310000
Mumbai: 2820000
Pune: 1980000


## --- Question 13: Category-Wise Sales ---

In [ ]:
# Calculate total sales for each product category across all stores.

# Display each category name with its total sales.

# Calculate total sales for each product category
category_total_sales = np.sum(sales_data, axis=0)

# Display category names with total sales
for category, total in zip(categories, category_total_sales):
    print(category + ":", total)

Electronics: 4290000
Groceries: 2185000
Clothing: 1600000
Furniture: 1415000
Beauty: 1010000
Sports: 1175000


## --- Question 14: Average Sales Per Store ---

In [ ]:
# Calculate the average sales generated by each store across all six product categories.

# Calculate average sales for each store
store_average_sales = np.mean(sales_data, axis=1)

# Display store names with average sales
for store, average in zip(stores, store_average_sales):
    print(store + ":", average)

Bengaluru: 378333.3333333333
Hyderabad: 382500.0
Chennai: 385000.0
Mumbai: 470000.0
Pune: 330000.0


## --- Question 15: Average Sales Per Category ---

In [ ]:
# Calculate the average sales of each product category across the five stores.

# Calculate average sales for each product category
category_average_sales = np.mean(sales_data, axis=0)

# Display category names with average sales
for category, average in zip(categories, category_average_sales):
    print(category + ":", average)

Electronics: 858000.0
Groceries: 437000.0
Clothing: 320000.0
Furniture: 283000.0
Beauty: 202000.0
Sports: 235000.0


### --- Question 16: Highest-Selling Store ---

In [ ]:
# Identify:

# Index of the store with the highest total sales
# Name of the store
# Total sales generated by that store
# Use np.argmax().

# Calculate total sales for each store
store_total_sales = np.sum(sales_data, axis=1)

# Find the index of the store with highest sales
highest_sales_index = np.argmax(store_total_sales)

# Get the store name
highest_sales_store = stores[highest_sales_index]

# Get the highest total sales
highest_sales = store_total_sales[highest_sales_index]

print("Index:", highest_sales_index)
print("Store Name:", highest_sales_store)
print("Total Sales:", highest_sales)

Index: 3
Store Name: Mumbai
Total Sales: 2820000


## -- Question 17: Lowest-Selling Store --

In [ ]:
# Identify the store with the lowest overall sales.

# Use np.argmin().

# Calculate total sales for each store
store_total_sales = np.sum(sales_data, axis=1)

# Find index of the store with lowest sales
lowest_sales_index = np.argmin(store_total_sales)

# Get store name
lowest_sales_store = stores[lowest_sales_index]

# Display result
print("Index:", lowest_sales_index)
print("Store with Lowest Sales:", lowest_sales_store)
print("Total Sales:", store_total_sales[lowest_sales_index])

Index: 4
Store with Lowest Sales: Pune
Total Sales: 1980000


### --- Question 18: Highest-Selling Category ---

In [ ]:
# Find the product category that generated the highest total sales across the company.

# Calculate total sales for each product category
category_total_sales = np.sum(sales_data, axis=0)

# Find index of the category with highest sales
highest_category_index = np.argmax(category_total_sales)

# Get category name
highest_category = categories[highest_category_index]

# Get total sales
highest_category_sales = category_total_sales[highest_category_index]

print("Index:", highest_category_index)
print("Category:", highest_category)
print("Total Sales:", highest_category_sales)

Index: 0
Category: Electronics
Total Sales: 4290000


### --- Question 19: Lowest-Selling Category ---

In [ ]:
## Find the product category with the lowest total sales across all stores.

# Calculate total sales for each product category
category_total_sales = np.sum(sales_data, axis=0)

# Find index of the category with lowest sales
lowest_category_index = np.argmin(category_total_sales)

# Get category name
lowest_category = categories[lowest_category_index]

# Get total sales
lowest_category_sales = category_total_sales[lowest_category_index]

print("Index:", lowest_category_index)
print("Category:", lowest_category)
print("Total Sales:", lowest_category_sales)

Index: 4
Category: Beauty
Total Sales: 1010000


### --- Part 5: Cost Analysis ---

## -- Question 20: Total Company Cost --

In [ ]:
# Calculate the total cost incurred by SmartMart across all stores and product categories.

# Calculate total cost across all stores and categories
total_cost = np.sum(cost_data)

print("Total Cost:", total_cost)

Total Cost: 8600000


### --- Question 21: Store-Wise Cost ---

In [ ]:
# Calculate the total cost incurred by each store.

# Calculate total cost for each store
store_total_cost = np.sum(cost_data, axis=1)

# Display store names with total cost
for store, total in zip(stores, store_total_cost):
    print(store + ":", total)

Bengaluru: 1665000
Hyderabad: 1685000
Chennai: 1710000
Mumbai: 2065000
Pune: 1475000


### --- Question 22: Category-Wise Cost ---

In [ ]:
# Calculate the total cost incurred for each product category across all stores.

# Calculate total cost for each product category
category_total_cost = np.sum(cost_data, axis=0)

# Display category names with total cost
for category, total in zip(categories, category_total_cost):
    print(category + ":", total)

Electronics: 3250000
Groceries: 1660000
Clothing: 1145000
Furniture: 1045000
Beauty: 665000
Sports: 835000


### --- Question 23: Most Expensive Store ---

In [ ]:
# Identify the store with the highest total operating cost.

# Calculate total cost for each store
store_total_cost = np.sum(cost_data, axis=1)

# Find the index of the highest cost
highest_cost_index = np.argmax(store_total_cost)

# Get the store name
highest_cost_store = stores[highest_cost_index]

# Get the highest total cost
highest_cost = store_total_cost[highest_cost_index]

print("Index:", highest_cost_index)
print("Store:", highest_cost_store)
print("Total Operating Cost:", highest_cost)

Index: 3
Store: Mumbai
Total Operating Cost: 2065000


## --- Question 24: Lowest-Cost Store ---

In [ ]:
# Identify the store with the lowest total cost.

# Calculate total cost for each store
store_total_cost = np.sum(cost_data, axis=1)

# Find the index of the lowest cost
lowest_cost_index = np.argmin(store_total_cost)

# Get the store name
lowest_cost_store = stores[lowest_cost_index]

# Get the lowest total cost
lowest_cost = store_total_cost[lowest_cost_index]

print("Index:", lowest_cost_index)
print("Store:", lowest_cost_store)
print("Total Cost:", lowest_cost)

Index: 4
Store: Pune
Total Cost: 1475000


# --- Question 25: Most Expensive Product Category ---

In [ ]:
# Determine which product category has the highest total cost across all stores.

# Calculate total cost for each product category
category_total_cost = np.sum(cost_data, axis=0)

# Find the index of the category with highest cost
highest_cost_category_index = np.argmax(category_total_cost)

# Get the category name
highest_cost_category = categories[highest_cost_category_index]

# Get the highest total cost
highest_category_cost = category_total_cost[highest_cost_category_index]

print("Index:", highest_cost_category_index)
print("Category:", highest_cost_category)
print("Total Cost:", highest_category_cost)

Index: 0
Category: Electronics
Total Cost: 3250000


# --- Part 6: Profit Analysis Using Two Arrays ---

# -- Question 26: Profit Matrix --

In [ ]:
# Calculate the profit generated for every store and product category.

# Use:

# profit_data = sales_data - cost_data
# Display the complete profit matrix.

# Calculate profit for every store and product category
profit_data = sales_data - cost_data

# Display the complete profit matrix
print("Profit Data:")
print(profit_data)

Profit Data:
[[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


# --- Question 27: Store-Wise Profit ---

In [ ]:
# Calculate the total profit generated by each store.

# Calculate total profit for each store
store_total_profit = np.sum(profit_data, axis=1)

# Display store names with total profit
for store, total in zip(stores, store_total_profit):
    print(store + ":", total)

Bengaluru: 605000
Hyderabad: 610000
Chennai: 600000
Mumbai: 755000
Pune: 505000


# --- Question 28: Category-Wise Profit ---

In [ ]:
# Calculate the total profit generated by each product category.

# Calculate total profit for each product category
category_total_profit = np.sum(profit_data, axis=0)

# Display category names with total profit
for category, total in zip(categories, category_total_profit):
    print(category + ":", total)

Electronics: 1040000
Groceries: 525000
Clothing: 455000
Furniture: 370000
Beauty: 345000
Sports: 340000


# --- Question 29: Most Profitable Store ---

In [ ]:
# Identify the store that generated the highest total profit.

# Display:

# Store name
# Total sales
# Total cost
# Total profit

# Find the index of the store with the highest total profit
highest_profit_index = np.argmax(store_total_profit)

# Get the store name
highest_profit_store = stores[highest_profit_index]

# Get total sales, cost, and profit
highest_profit_sales = store_total_sales[highest_profit_index]
highest_profit_cost = store_total_cost[highest_profit_index]
highest_profit = store_total_profit[highest_profit_index]

# Display the results
print("Store Name:", highest_profit_store)
print("Total Sales:", highest_profit_sales)
print("Total Cost:", highest_profit_cost)
print("Total Profit:", highest_profit)

Store Name: Mumbai
Total Sales: 2820000
Total Cost: 2065000
Total Profit: 755000


# --- Question 30: Least Profitable Store ---

In [ ]:
# Identify the store that generated the lowest total profit.

# Find the index of the store with the lowest total profit
lowest_profit_index = np.argmin(store_total_profit)

# Get the store name
lowest_profit_store = stores[lowest_profit_index]

# Get the lowest total profit
lowest_profit = store_total_profit[lowest_profit_index]

# Display the results
print("Store Name:", lowest_profit_store)
print("Total Profit:", lowest_profit)

Store Name: Pune
Total Profit: 505000


# --- Question 31: Most Profitable Category ---

In [ ]:
# Find the category with the highest total profit across all stores.

# Calculate total profit for each product category
category_total_profit = np.sum(profit_data, axis=0)

# Find the index of the category with the highest profit
highest_profit_category_index = np.argmax(category_total_profit)

# Get the category name
highest_profit_category = categories[highest_profit_category_index]

# Get the highest total profit
highest_category_profit = category_total_profit[highest_profit_category_index]

# Display the results
print("Category:", highest_profit_category)
print("Total Profit:", highest_category_profit)

Category: Electronics
Total Profit: 1040000


# --- Question 32: Least Profitable Category ---

In [ ]:
# Find the category with the lowest total profit.

# Calculate total profit for each product category
category_total_profit = np.sum(profit_data, axis=0)

# Find the index of the category with the lowest profit
lowest_profit_category_index = np.argmin(category_total_profit)

# Get the category name
lowest_profit_category = categories[lowest_profit_category_index]

# Get the lowest total profit
lowest_category_profit = category_total_profit[lowest_profit_category_index]

# Display the results
print("Category:", lowest_profit_category)
print("Total Profit:", lowest_category_profit)

Category: Sports
Total Profit: 340000


# --- Question 33: Maximum Individual Profit ---

In [ ]:
# Find the highest profit generated by any single store-category combination.

# Display:

# Profit amount
# Store name
# Product category
# Use np.unravel_index().

# Find the highest profit value
highest_profit = np.max(profit_data)

# Find the row and column index of the highest profit
highest_profit_index = np.unravel_index(
    np.argmax(profit_data),
    profit_data.shape
)

# Get row and column indexes
store_index = highest_profit_index[0]
category_index = highest_profit_index[1]

# Get store and category names
store_name = stores[store_index]
category_name = categories[category_index]

# Display results
print("Highest Profit:", highest_profit)
print("Store Name:", store_name)
print("Product Category:", category_name)

Highest Profit: 260000
Store Name: Mumbai
Product Category: Electronics


# --- Question 34: Minimum Individual Profit ---

In [ ]:
# Find the smallest profit generated by a store-category combination.

# Display the corresponding store and category.

# Find the smallest profit value
smallest_profit = np.min(profit_data)

# Find the row and column index of the smallest profit
smallest_profit_index = np.unravel_index(
    np.argmin(profit_data),
    profit_data.shape
)

# Get row and column indexes
store_index = smallest_profit_index[0]
category_index = smallest_profit_index[1]

# Get store and category names
store_name = stores[store_index]
category_name = categories[category_index]

# Display results
print("Smallest Profit:", smallest_profit)
print("Store Name:", store_name)
print("Product Category:", category_name)

Smallest Profit: 55000
Store Name: Pune
Product Category: Furniture


# --- Part 7: Profit Margin Analysis ---

# -- Question 35: Profit Margin Matrix ---

In [ ]:
# Calculate the profit margin percentage for every store-category combination.

# Use:

# profit_margin = (profit_data / sales_data) * 100
# Round the result to two decimal places.

# Calculate profit margin percentage
profit_margin = (profit_data / sales_data) * 100

# Round the result to 2 decimal places
profit_margin = np.round(profit_margin, 2)

# Display the complete profit margin matrix
print("Profit Margin Percentage:")
print(profit_margin)

Profit Margin Percentage:
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


# --- Question 36: Store-Wise Profit Margin ---

In [ ]:
# Calculate the overall profit margin percentage for each store using:

# Store Profit Margin =
# Total Store Profit / Total Store Sales × 100

# Calculate overall profit margin for each store
store_profit_margin = (store_total_profit / store_total_sales) * 100

# Round to 2 decimal places
store_profit_margin = np.round(store_profit_margin, 2)

# Display store names with profit margin
for store, margin in zip(stores, store_profit_margin):
    print(store + ":", margin, "%")

Bengaluru: 26.65 %
Hyderabad: 26.58 %
Chennai: 25.97 %
Mumbai: 26.77 %
Pune: 25.51 %


# --- Question 37: Category-Wise Profit Margin ---

In [ ]:
# Calculate the overall profit margin percentage for each product category.

# Calculate overall profit margin for each product category
category_profit_margin = (category_total_profit / category_total_sales) * 100

# Round to 2 decimal places
category_profit_margin = np.round(category_profit_margin, 2)

# Display category names with profit margin
for category, margin in zip(categories, category_profit_margin):
    print(category + ":", margin, "%")

Electronics: 24.24 %
Groceries: 24.03 %
Clothing: 28.44 %
Furniture: 26.15 %
Beauty: 34.16 %
Sports: 28.94 %


# --- Question 38: Best Store by Profit Margin ---

In [ ]:
# Identify the store with the highest overall profit margin.

# Find the index of the store with the highest profit margin
highest_margin_index = np.argmax(store_profit_margin)

# Get the store name
highest_margin_store = stores[highest_margin_index]

# Get the profit margin
highest_margin = store_profit_margin[highest_margin_index]

# Display the result
print("Store:", highest_margin_store)
print("Highest Profit Margin:", highest_margin, "%")

Store: Mumbai
Highest Profit Margin: 26.77 %


# --- Question 39: Best Category by Profit Margin ---

In [ ]:
# Identify the product category with the highest profit margin.

# Find the index of the category with the highest profit margin
highest_category_margin_index = np.argmax(category_profit_margin)

# Get the category name
highest_category_margin = categories[highest_category_margin_index]

# Get the profit margin value
highest_margin = category_profit_margin[highest_category_margin_index]

# Display the result
print("Category:", highest_category_margin)
print("Highest Profit Margin:", highest_margin, "%")

Category: Beauty
Highest Profit Margin: 34.16 %


# --- Question 40: Low-Margin Transactions ---

In [ ]:
# # Management considers a profit margin below 22% to be weak.

# Find all store-category combinations where the profit margin is below 22%.

# Display:

# Store
# Category
# Sales
# Cost
# Profit
# Profit margin
# Use Boolean indexing.

In [ ]:
# Find the index of the category with the highest profit margin
highest_category_margin_index = np.argmax(category_profit_margin)

# Get the category name
highest_category_margin = categories[highest_category_margin_index]

# Get the profit margin value
highest_margin = category_profit_margin[highest_category_margin_index]

# Display the result
print("Category:", highest_category_margin)
print("Highest Profit Margin:", highest_margin, "%")

Category: Beauty
Highest Profit Margin: 34.16 %


# --- Part 8: Boolean Filtering ---

# --- Question 41: High Sales Values ---

In [ ]:
# Find all sales values below ₹2,00,000.
# Find all sales values greater than 5,00,000
high_sales = sales_data[sales_data > 500000]

print("Sales greater than 5,00,000:")
print(high_sales)


Sales greater than 5,00,000:
[ 850000  780000  920000 1050000  510000  690000]


# --- Question 42: Low Sales Values ---

In [ ]:
# Find all sales values below ₹2,00,000.

# # Find all sales values below ₹2,00,000
low_sales = sales_data[sales_data < 200000]

print("Sales values below ₹2,00,000:")
print(low_sales)

Sales values below ₹2,00,000:
[190000 185000 175000]


# --- Question 43: High Profit Values ---

In [ ]:
# Find all store-category combinations where profit is greater than ₹1,50,000.

# Find row and column indexes where profit is greater than 150000
store_indexes, category_indexes = np.where(profit_data > 150000)

# Display store, category, and profit
for store_index, category_index in zip(store_indexes, category_indexes):
    print(
        "Store:", stores[store_index],
        "| Category:", categories[category_index],
        "| Profit:", profit_data[store_index, category_index]
    )

Store: Bengaluru | Category: Electronics | Profit: 210000
Store: Hyderabad | Category: Electronics | Profit: 190000
Store: Chennai | Category: Electronics | Profit: 220000
Store: Mumbai | Category: Electronics | Profit: 260000
Store: Pune | Category: Electronics | Profit: 160000


# --- Question 44: Moderate Sales Range ---

In [ ]:
# Find sales values between ₹2,50,000 and ₹5,00,000.

# Use np.logical_and().

# Find sales values between 250000 and 500000
sales_between = sales_data[
    np.logical_and(sales_data >= 250000, sales_data <= 500000)
]

print("Sales values between ₹2,50,000 and ₹5,00,000:")
print(sales_between)

# --- Question 45: Premium Performance ---

In [ ]:
# A store-category combination is considered premium when:

# Sales are greater than ₹5,00,000
# Profit is greater than ₹1,50,000
# Find all premium-performing combinations.

# Find premium-performing combinations
premium_mask = np.logical_and(
    sales_data > 500000,
    profit_data > 150000
)

# Get store and category indexes
store_indexes, category_indexes = np.where(premium_mask)

# Display results
for store_index, category_index in zip(store_indexes, category_indexes):
    print(
        stores[store_index],
        "-",
        categories[category_index],
        "| Sales:", sales_data[store_index, category_index],
        "| Profit:", profit_data[store_index, category_index]
    )

Bengaluru - Electronics | Sales: 850000 | Profit: 210000
Hyderabad - Electronics | Sales: 780000 | Profit: 190000
Chennai - Electronics | Sales: 920000 | Profit: 220000
Mumbai - Electronics | Sales: 1050000 | Profit: 260000
Pune - Electronics | Sales: 690000 | Profit: 160000


# --- Question 46: Underperforming Combinations ---

In [ ]:
# # A store-category combination is considered underperforming when:

# Sales are below ₹2,50,000
# Profit margin is below 25%
# Find all such combinations.

# Find underperforming combinations
underperforming_mask = np.logical_and(
    sales_data < 250000,
    profit_margin < 25
)

# Get store and category indexes
store_indexes, category_indexes = np.where(underperforming_mask)

# Display results
for store_index, category_index in zip(store_indexes, category_indexes):
    print(
        stores[store_index],
        "-",
        categories[category_index],
        "| Sales:", sales_data[store_index, category_index],
        "| Profit Margin:", profit_margin[store_index, category_index], "%"
    )

Pune - Furniture | Sales: 225000 | Profit Margin: 24.44 %


# --- Question 47: Category Performance Classification ---

In [ ]:
# Create a new array that classifies every sales value as:

# "High" when sales are at least ₹5,00,000
# "Medium" when sales are between ₹2,50,000 and ₹4,99,999
# "Low" when sales are below ₹2,50,000
# Use np.where() or np.select().

# Classify sales values as High, Medium, or Low
sales_classification = np.where(
    sales_data >= 500000,
    "High",
    np.where(sales_data >= 250000, "Medium", "Low")
)

print("Sales Classification:")
print(sales_classification)

Sales Classification:
[['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Low' 'Low' 'Low']]


# --- Part 9: Target-Based Analysis ---

In [ ]:
# Use the following category-wise monthly sales targets:

# sales_targets = np.array([
#     800000,  # Electronics
#     450000,  # Groceries
#     320000,  # Clothing
#     300000,  # Furniture
#     200000,  # Beauty
#     230000   # Sports
# ])


# --- Question 48: Target Comparison ---

In [ ]:
# Compare every store’s category sales against sales_targets.

# Use NumPy broadcasting.


sales_targets = np.array([
    800000, 450000, 300000, 280000, 200000, 220000
])
# Create sales targets for each category
sales_targets = np.array([
    800000, 450000, 300000, 280000, 200000, 220000
])

# Compare every store's category sales against sales_targets
target_achieved = sales_data >= sales_targets

print("Target Achievement:")
print(target_achieved)

Target Achievement:
[[ True False  True False False  True]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


# --- Question 49: Target Achievement Matrix ---

In [ ]:
# Create a Boolean array where:

# True means the store achieved the category target
# False means the store failed to achieve the target

sales_targets = np.array([
    800000, 450000, 300000,
    280000, 200000, 220000
])
# Compare sales with targets using broadcasting
target_achieved = sales_data >= sales_targets

# Display the Boolean matrix
print("Target Achievement Matrix:")
print(target_achieved)


Target Achievement Matrix:
[[ True False  True False False  True]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


# --- Question 50: Target Achievement Count ---

In [ ]:
# Calculate the number of categories in which each store achieved its target.

# Calculate number of categories where each store achieved the target
categories_achieved = np.sum(target_achieved, axis=1)

# Display store names with number of targets achieved
for store, count in zip(stores, categories_achieved):
    print(store + ":", count)


Bengaluru: 3
Hyderabad: 4
Chennai: 2
Mumbai: 6
Pune: 0
