<a href="https://colab.research.google.com/github/khan085796-collab/Aftab_edurkon_2026-DS/blob/main/project_9_Numpy_Assignment(50_120).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# === NumPy Retail Analytics Assignment (50 - 100) ===

In [ ]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])

print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


# --- Question 51: Best Target-Performing Store ---

In [ ]:
# Create sales targets
sales_targets = np.array([
    800000, 450000, 300000,
    280000, 200000, 220000
])

# Create target achievement matrix
target_achieved = sales_data >= sales_targets

# Count achieved targets for each store
categories_achieved = np.sum(target_achieved, axis=1)

In [ ]:
# Find the store that achieved the highest number of category targets.

# Find the store with the highest number of targets achieved
highest_target_index = np.argmax(categories_achieved)

highest_target_store = stores[highest_target_index]
highest_target_count = categories_achieved[highest_target_index]

print("Store:", highest_target_store)
print("Number of Targets Achieved:", highest_target_count)

Store: Mumbai
Number of Targets Achieved: 6


## ---- Question 52: Target Achievement by Category ---

In [ ]:
#Calculate how many stores achieved the target for each product category.

# Calculate how many stores achieved the target for each category
stores_achieved = np.sum(target_achieved, axis=0)

# Display category names with number of stores that achieved the target
for category, count in zip(categories, stores_achieved):
    print(category + ":", count)

Electronics: 3
Groceries: 2
Clothing: 3
Furniture: 2
Beauty: 2
Sports: 3


# --- Question 53: Sales Target Variance ---

In [ ]:
# Calculate the difference between actual sales and target sales for every store.

# Use:

# Variance = Actual Sales - Target Sales

# Calculate variance between actual sales and target sales
sales_variance = sales_data - sales_targets

print("Sales Variance:")
print(sales_variance)

Sales Variance:
[[  50000  -30000   10000   -5000  -10000    5000]
 [ -20000   10000   -5000   30000   10000   20000]
 [ 120000  -60000   40000  -20000  -15000   -5000]
 [ 250000   60000   75000   65000   50000   70000]
 [-110000  -45000  -20000  -55000  -25000  -15000]]


# --- Question 54: Percentage Above or Below Target ---

In [ ]:
# Calculate the percentage variance from the target using:

# Percentage Variance =
# (Actual Sales - Target Sales) / Target Sales × 100

# Calculate percentage variance
percentage_variance = (
    (sales_data - sales_targets) / sales_targets
) * 100

# Round to 2 decimal places
percentage_variance = np.round(percentage_variance, 2)

print("Percentage Variance:")
print(percentage_variance)

Percentage Variance:
[[  6.25  -6.67   3.33  -1.79  -5.     2.27]
 [ -2.5    2.22  -1.67  10.71   5.     9.09]
 [ 15.   -13.33  13.33  -7.14  -7.5   -2.27]
 [ 31.25  13.33  25.    23.21  25.    31.82]
 [-13.75 -10.    -6.67 -19.64 -12.5   -6.82]]


# --- Question 55: Stores Missing Electronics Target ---

In [ ]:
# Identify stores that failed to achieve the Electronics sales target.

# Find stores that failed to achieve the Electronics target
failed_electronics = stores[sales_data[:, 0] < sales_targets[0]]

print("Stores that failed to achieve Electronics target:")
print(failed_electronics)

Stores that failed to achieve Electronics target:
['Hyderabad' 'Pune']


# --- Question 56: Stores Achieving All Targets ---

In [ ]:
# Check whether any store achieved its target in all six product categories.

# Use np.all().

# Check whether each store achieved all 6 category targets
all_targets_achieved = np.all(target_achieved, axis=1)

print("All Targets Achieved:")
print(all_targets_achieved)

# Display stores that achieved all targets
print("Stores that achieved all targets:")
print(stores[all_targets_achieved])

All Targets Achieved:
[False False False  True False]
Stores that achieved all targets:
['Mumbai']


# --- Question 57: Stores Achieving At Least One Target ---

In [ ]:
#Identify stores that achieved at least one category target.

# Use np.any().

# Check whether each store achieved at least one target
at_least_one_target = np.any(target_achieved, axis=1)

print("At Least One Target Achieved:")
print(at_least_one_target)

# Display the stores
print("Stores that achieved at least one target:")
print(stores[at_least_one_target])

At Least One Target Achieved:
[ True  True  True  True False]
Stores that achieved at least one target:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']


=== Part 10: Discount Scenario
SmartMart plans to offer category-wise discounts:

discount_rates = np.array([
    
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  # Furniture: 12%
    0.08,  # Beauty: 8%
    0.10   # Sports: 10%
]) ====

# --- Question 58: Discount Amount Matrix ---

In [ ]:
# Calculate the discount amount for each store-category combination.

# Use broadcasting.

# Example discount percentage for each product category
discount_rates = np.array([10, 5, 8, 12, 15, 7])

# Calculate discount amount
discount_amount = sales_data * (discount_rates / 100)

print("Discount Amount:")
print(discount_amount)

Discount Amount:
[[ 85000.  21000.  24800.  33000.  28500.  15750.]
 [ 78000.  23000.  23600.  37200.  31500.  16800.]
 [ 92000.  19500.  27200.  31200.  27750.  15050.]
 [105000.  25500.  30000.  41400.  37500.  20300.]
 [ 69000.  20250.  22400.  27000.  26250.  14350.]]


# --- Question 59: Sales After Discount ---

In [ ]:
# Calculate the net sales value after applying the category-wise discounts.

# Calculate net sales after discount
net_sales = sales_data - discount_amount

print("Net Sales:")
print(net_sales)

Net Sales:
[[765000. 399000. 285200. 242000. 161500. 209250.]
 [702000. 437000. 271400. 272800. 178500. 223200.]
 [828000. 370500. 312800. 228800. 157250. 199950.]
 [945000. 484500. 345000. 303600. 212500. 269700.]
 [621000. 384750. 257600. 198000. 148750. 190650.]]


# --- Question 60: Profit After Discount ---

In [ ]:
# Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

# Calculate new profit after applying discounts
new_profit = net_sales - cost_data

print("New Profit:")
print(new_profit)

New Profit:
[[125000.  84000.  65200.  37000.  36500.  49250.]
 [112000.  87000.  61400.  47800.  38500.  53200.]
 [128000.  75500.  67800.  33800.  37250.  44950.]
 [155000.  94500.  80000.  53600.  47500.  64700.]
 [ 91000.  74750.  52600.  28000.  33750.  45650.]]


# --- Question 61: Profit Margin After Discount ---

In [ ]:
# Calculate the new profit margin after applying discounts.

# Calculate new profit margin percentage
new_profit_margin = (new_profit / net_sales) * 100

# Round to 2 decimal places
new_profit_margin = np.round(new_profit_margin, 2)

print("New Profit Margin:")
print(new_profit_margin)

New Profit Margin:
[[16.34 21.05 22.86 15.29 22.6  23.54]
 [15.95 19.91 22.62 17.52 21.57 23.84]
 [15.46 20.38 21.68 14.77 23.69 22.48]
 [16.4  19.5  23.19 17.65 22.35 23.99]
 [14.65 19.43 20.42 14.14 22.69 23.94]]


# --- Question 62: Loss-Making Transactions ---

In [ ]:
# Check whether any store-category combination becomes loss-making after discounts.

# Display the affected store and category names.

# Check whether any combination becomes loss-making
has_loss = np.any(new_profit < 0)

print("Any loss-making combination:", has_loss)

# Find the indexes of loss-making combinations
store_indexes, category_indexes = np.where(new_profit < 0)

# Display affected stores and categories
for store_index, category_index in zip(store_indexes, category_indexes):
    print(
        "Store:", stores[store_index],
        "| Category:", categories[category_index],
        "| New Profit:", new_profit[store_index, category_index]
    )

Any loss-making combination: False


# --- Question 63: Discount Impact ---

In [ ]:
# Calculate how much total revenue the company loses because of the proposed discounts.

# Calculate total revenue lost due to discounts
total_revenue_loss = np.sum(discount_amount)

print("Total Revenue Lost:", total_revenue_loss)

Total Revenue Lost: 1069800.0


# --- Question 64: Store Most Affected by Discounts ---

In [ ]:
# Identify the store that loses the highest amount of revenue due to discounts.

# Calculate total revenue loss due to discounts for each store
store_discount_loss = np.sum(discount_amount, axis=1)

# Find the index of the store with the highest revenue loss
highest_loss_index = np.argmax(store_discount_loss)

# Get the store name
highest_loss_store = stores[highest_loss_index]

# Get the revenue loss amount
highest_loss_amount = store_discount_loss[highest_loss_index]

print("Store:", highest_loss_store)
print("Highest Revenue Loss:", highest_loss_amount)

Store: Mumbai
Highest Revenue Loss: 259700.0


=== Part 11: Tax and Price Adjustment
The government introduces category-wise tax rates:

tax_rates = np.array([
    
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
]) ---

# --- Question 65: Tax Collection Matrix ---

In [ ]:
# Calculate the tax collected on sales for each store and category.

# Define tax rate
tax_rate = 18

# Calculate tax on sales
tax_amount = sales_data * (tax_rate / 100)

print("Tax Amount:")
print(tax_amount)

Tax Amount:
[[153000.  75600.  55800.  49500.  34200.  40500.]
 [140400.  82800.  53100.  55800.  37800.  43200.]
 [165600.  70200.  61200.  46800.  33300.  38700.]
 [189000.  91800.  67500.  62100.  45000.  52200.]
 [124200.  72900.  50400.  40500.  31500.  36900.]]


# --- Question 66: Sales Including Tax ---

In [ ]:
# Calculate the final customer billing value after adding tax.

# Calculate final customer billing value
final_billing = sales_data + tax_amount

print("Final Customer Billing Value:")
print(final_billing)

Final Customer Billing Value:
[[1003000.  495600.  365800.  324500.  224200.  265500.]
 [ 920400.  542800.  348100.  365800.  247800.  283200.]
 [1085600.  460200.  401200.  306800.  218300.  253700.]
 [1239000.  601800.  442500.  407100.  295000.  342200.]
 [ 814200.  477900.  330400.  265500.  206500.  241900.]]


# --- Question 67: Store-Wise Tax Collection ---

In [ ]:
# Calculate the total tax collected by each store.

# Calculate total tax collected by each store
store_total_tax = np.sum(tax_amount, axis=1)

# Display store names with total tax
for store, total in zip(stores, store_total_tax):
    print(store + ":", total)

Bengaluru: 408600.0
Hyderabad: 413100.0
Chennai: 415800.0
Mumbai: 507600.0
Pune: 356400.0


# --- Question 68: Category-Wise Tax Collection ---

In [ ]:
# Calculate total tax collected for each category.

# Calculate total tax collected for each category
category_total_tax = np.sum(tax_amount, axis=0)

# Display category names with total tax
for category, total in zip(categories, category_total_tax):
    print(category + ":", total)

Electronics: 772200.0
Groceries: 393300.0
Clothing: 288000.0
Furniture: 254700.0
Beauty: 181800.0
Sports: 211500.0


# --- Question 69: Highest Tax-Contributing Store ---

In [ ]:
# Identify the store that contributes the highest tax amount.

# Find the index of the store with the highest total tax
highest_tax_index = np.argmax(store_total_tax)

# Get the store name
highest_tax_store = stores[highest_tax_index]

# Get the highest tax amount
highest_tax_amount = store_total_tax[highest_tax_index]

print("Store:", highest_tax_store)
print("Highest Tax Amount:", highest_tax_amount)

Store: Mumbai
Highest Tax Amount: 507600.0


# --- Part 12: Array Modification ---

# --- Question 70: Updated Pune Electronics Sales ---

In [ ]:
# The Pune store reports that its Electronics sales were entered incorrectly.

# Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

# Make the change in a copied array without modifying the original array.

# Create a copy of the original sales_data
updated_sales_data = sales_data.copy()

# Update Pune Electronics sales
updated_sales_data[4, 0] = 740000

print("Updated Sales Data:")
print(updated_sales_data)

Updated Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 740000  405000  280000  225000  175000  205000]]


# --- Question 71: Revised Beauty Cost ---

In [ ]:
# Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

# Create an updated cost array.

# Create a copy of the original cost_data
updated_cost_data = cost_data.copy()

# Reduce Beauty costs by 8% for all stores
updated_cost_data[:, 4] = updated_cost_data[:, 4] * 0.92

print("Updated Cost Data:")
print(updated_cost_data)

Updated Cost Data:
[[640000 315000 220000 205000 115000 160000]
 [590000 350000 210000 225000 128800 170000]
 [700000 295000 245000 195000 110400 155000]
 [790000 390000 265000 250000 151800 205000]
 [530000 310000 205000 170000 105800 145000]]


# --- Question 72: Furniture Cost Increase ---

In [ ]:
# Furniture costs increase by 12% for all stores.

# Update only the Furniture column.

# Create a copy of the original cost_data
updated_cost_data = cost_data.copy()

# Increase Furniture costs by 12% for all stores
updated_cost_data[:, 3] = updated_cost_data[:, 3] * 1.12

print("Updated Cost Data:")
print(updated_cost_data)

Updated Cost Data:
[[640000 315000 220000 229600 125000 160000]
 [590000 350000 210000 252000 140000 170000]
 [700000 295000 245000 218400 120000 155000]
 [790000 390000 265000 280000 165000 205000]
 [530000 310000 205000 190400 115000 145000]]


# --- Question 73: Store Closure Simulation ---

In [ ]:
# Assume the Pune store is temporarily closed.

# Remove Pune’s sales and cost data from the analysis using np.delete().

# Create a copy of the original cost_data
updated_cost_data = cost_data.copy()

# Increase Furniture costs by 12% for all stores
updated_cost_data[:, 3] = updated_cost_data[:, 3] * 1.12

print("Updated Cost Data:")
print(updated_cost_data)

Updated Cost Data:
[[640000 315000 220000 229600 125000 160000]
 [590000 350000 210000 252000 140000 170000]
 [700000 295000 245000 218400 120000 155000]
 [790000 390000 265000 280000 165000 205000]
 [530000 310000 205000 190400 115000 145000]]


# --- Question 74: Adding a New Store ---

In [ ]:
# A new Delhi store is opened with the following data:

# delhi_sales = np.array([
#     880000, 475000, 330000, 290000, 215000, 250000
# ])

# delhi_cost = np.array([
#     665000, 360000, 235000, 215000, 145000, 180000
# ])
# Add Delhi to both arrays using np.vstack().

# Also add "Delhi" to the stores array.

# Delhi sales data
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])

# Delhi cost data
delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])

# Add Delhi to sales_data
updated_sales_data = np.vstack((sales_data, delhi_sales))

# Add Delhi to cost_data
updated_cost_data = np.vstack((cost_data, delhi_cost))

# Add Delhi to stores array
updated_stores = np.append(stores, "Delhi")

print("Updated Stores:")
print(updated_stores)

print("\nUpdated Sales Data:")
print(updated_sales_data)

print("\nUpdated Cost Data:")
print(updated_cost_data)

Updated Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']

Updated Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]

Updated Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]
 [665000 360000 235000 215000 145000 180000]]


# --- Question 75: Adding a New Product Category ---

In [ ]:
# SmartMart starts selling Home Appliances.

# home_appliance_sales = np.array([
#     360000,
#     325000,
#     390000,
#     420000,
#     295000
# ])

# home_appliance_cost = np.array([
#     265000,
#     240000,
#     285000,
#     305000,
#     225000
# ])
# Add the new category as a column using np.column_stack() or np.hstack().

# Home Appliances sales data
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])

# Home Appliances cost data
home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])

# Add Home Appliances as a new column
updated_sales_data = np.column_stack(
    (sales_data, home_appliance_sales)
)

updated_cost_data = np.column_stack(
    (cost_data, home_appliance_cost)
)

# Add the new category name
updated_categories = np.append(categories, "Home Appliances")

print("Updated Categories:")
print(updated_categories)

print("\nUpdated Sales Data:")
print(updated_sales_data)

print("\nUpdated Cost Data:")
print(updated_cost_data)

Updated Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports'
 'Home Appliances']

Updated Sales Data:
[[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]

Updated Cost Data:
[[640000 315000 220000 205000 125000 160000 265000]
 [590000 350000 210000 225000 140000 170000 240000]
 [700000 295000 245000 195000 120000 155000 285000]
 [790000 390000 265000 250000 165000 205000 305000]
 [530000 310000 205000 170000 115000 145000 225000]]


# === Part 13: Sorting and Ranking ===

# --- Question 76: Sort Stores by Sales ---

In [ ]:
# Sort stores in ascending order based on total sales.

# Display store names and sales totals.

# Calculate total sales for each store
store_total_sales = np.sum(sales_data, axis=1)

# Get indexes that sort the sales in ascending order
sorted_indexes = np.argsort(store_total_sales)

# Display stores and their total sales in ascending order
for index in sorted_indexes:
    print(stores[index] + ":", store_total_sales[index])

Pune: 1980000
Bengaluru: 2270000
Hyderabad: 2295000
Chennai: 2310000
Mumbai: 2820000


# --- Question 77: Rank Stores by Profit ---

In [ ]:
# Rank stores from highest to lowest total profit.

# Use np.argsort().

# Calculate profit for every store and category
profit_data = sales_data - cost_data

# Calculate total profit for each store
store_total_profit = np.sum(profit_data, axis=1)

# Sort from highest to lowest profit
sorted_indexes = np.argsort(store_total_profit)[::-1]

# Display ranking
for index in sorted_indexes:
    print(stores[index] + ":", store_total_profit[index])

Mumbai: 755000
Hyderabad: 610000
Bengaluru: 605000
Chennai: 600000
Pune: 505000


# --- Question 78: Sort Categories by Revenue ---

In [ ]:
# Sort product categories from highest to lowest total revenue.

# Calculate total sales for each product category
category_total_sales = np.sum(sales_data, axis=0)

# Get indexes sorted from highest to lowest
sorted_indexes = np.argsort(category_total_sales)[::-1]

# Display categories and their total revenue
for index in sorted_indexes:
    print(categories[index] + ":", category_total_sales[index])

Electronics: 4290000
Groceries: 2185000
Clothing: 1600000
Furniture: 1415000
Sports: 1175000
Beauty: 1010000


# --- Question 79: Top Three Store-Category Sales ---

In [ ]:
# Find the three highest individual sales values in the complete sales matrix.

# Display their:

# Sales value
# Store name
# Category name

# Find the indexes of the 3 highest sales values
top_3_indexes = np.argsort(sales_data, axis=None)[-3:][::-1]

# Convert flat indexes into row and column indexes
store_indexes, category_indexes = np.unravel_index(
    top_3_indexes,
    sales_data.shape
)

# Display the results
for store_index, category_index in zip(store_indexes, category_indexes):
    print(
        "Sales:", sales_data[store_index, category_index],
        "| Store:", stores[store_index],
        "| Category:", categories[category_index]
    )

Sales: 1050000 | Store: Mumbai | Category: Electronics
Sales: 920000 | Store: Chennai | Category: Electronics
Sales: 850000 | Store: Bengaluru | Category: Electronics


# --- Question 80: Bottom Three Profits ---

In [ ]:
# Find the three lowest profit values in the profit matrix.

# Find the indexes of the 3 lowest profit values
lowest_3_indexes = np.argsort(profit_data, axis=None)[:3]

# Convert flat indexes into row and column indexes
store_indexes, category_indexes = np.unravel_index(
    lowest_3_indexes,
    profit_data.shape
)

# Display the results
for store_index, category_index in zip(store_indexes, category_indexes):
    print(
        "Profit:", profit_data[store_index, category_index],
        "| Store:", stores[store_index],
        "| Category:", categories[category_index]
    )

Profit: 55000 | Store: Pune | Category: Furniture
Profit: 60000 | Store: Pune | Category: Sports
Profit: 60000 | Store: Chennai | Category: Sports


# === Part 14: Statistical Analysis ===

# --- Question 81: Sales Statistics ---

In [ ]:
# Calculate the following for the complete sales array:

# Minimum
# Maximum
# Mean
# Median
# Standard deviation
# Variance
# 25th percentile
# 50th percentile
# 75th percentile

# Minimum
minimum = np.min(sales_data)

# Maximum
maximum = np.max(sales_data)

# Mean
mean = np.mean(sales_data)

# Median
median = np.median(sales_data)

# Standard deviation
std_deviation = np.std(sales_data)

# Variance
variance = np.var(sales_data)

# Percentiles
percentile_25 = np.percentile(sales_data, 25)
percentile_50 = np.percentile(sales_data, 50)
percentile_75 = np.percentile(sales_data, 75)

# Display results
print("Minimum:", minimum)
print("Maximum:", maximum)
print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_deviation)
print("Variance:", variance)
print("25th Percentile:", percentile_25)
print("50th Percentile:", percentile_50)
print("75th Percentile:", percentile_75)

Minimum: 175000
Maximum: 1050000
Mean: 389166.6666666667
Median: 302500.0
Standard Deviation: 230322.53954448793
Variance: 53048472222.222206
25th Percentile: 228750.0
50th Percentile: 302500.0
75th Percentile: 416250.0


# --- Question 82: Store-Wise Standard Deviation ---

In [ ]:
# #Calculate the sales standard deviation for every store.

# Use this value to determine which store has the most variation between product categories.

# Calculate sales standard deviation for each store
store_sales_std = np.std(sales_data, axis=1)

# Display each store with its standard deviation
for store, std in zip(stores, store_sales_std):
    print(store + ":", round(std, 2))

# Find the store with the highest variation
highest_variation_index = np.argmax(store_sales_std)

print("\nStore with the most variation:", stores[highest_variation_index])
print("Standard Deviation:", round(store_sales_std[highest_variation_index], 2))

Bengaluru: 223059.53
Hyderabad: 194502.57
Chennai: 249265.59
Mumbai: 271860.87
Pune: 177200.45

Store with the most variation: Mumbai
Standard Deviation: 271860.87


# --- Question 83: Category-Wise Standard Deviation ---

In [ ]:
# Determine which product category has the highest variation in sales across stores.

# Calculate sales standard deviation for each product category
category_sales_std = np.std(sales_data, axis=0)

# Display each category with its standard deviation
for category, std in zip(categories, category_sales_std):
    print(category + ":", round(std, 2))

# Find the category with the highest variation
highest_variation_index = np.argmax(category_sales_std)

print("\nCategory with the most variation:",
      categories[highest_variation_index])

print("Standard Deviation:",
      round(category_sales_std[highest_variation_index], 2))

Electronics: 122539.79
Groceries: 43312.82
Clothing: 33911.65
Furniture: 41303.75
Beauty: 26570.66
Sports: 29832.87

Category with the most variation: Electronics
Standard Deviation: 122539.79


# --- Question 84: Sales Above Company Average ---

In [ ]:
# Calculate the company-wide average sales value.

# Count how many store-category sales values are above this average.

# Calculate company-wide average sales
company_average_sales = np.mean(sales_data)

# Count sales values above the company average
above_average_count = np.sum(sales_data > company_average_sales)

print("Company-wide Average Sales:", company_average_sales)
print("Number of sales values above average:", above_average_count)

Company-wide Average Sales: 389166.6666666667
Number of sales values above average: 10


# --- Question 85: Outlier Detection ---

In [ ]:
# Treat any sales value greater than:

# Mean + 1.5 × Standard Deviation
# as a high-value outlier.

# Identify all such sales values.

# Calculate mean and standard deviation
mean_sales = np.mean(sales_data)
std_sales = np.std(sales_data)

# Calculate high-value outlier threshold
outlier_threshold = mean_sales + (1.5 * std_sales)

print("Outlier Threshold:", outlier_threshold)

# Find indexes of high-value outliers
store_indexes, category_indexes = np.where(
    sales_data > outlier_threshold
)

# Display the outliers
for store_index, category_index in zip(store_indexes, category_indexes):
    print(
        "Sales:", sales_data[store_index, category_index],
        "| Store:", stores[store_index],
        "| Category:", categories[category_index]
    )

Outlier Threshold: 734650.4759833985
Sales: 850000 | Store: Bengaluru | Category: Electronics
Sales: 780000 | Store: Hyderabad | Category: Electronics
Sales: 920000 | Store: Chennai | Category: Electronics
Sales: 1050000 | Store: Mumbai | Category: Electronics


# === Part 15: Reshaping and Transformation ===

# --- Question 86: Flatten Sales Data ---

In [ ]:
# # Convert the two-dimensional sales array into a one-dimensional array using:

# flatten()
# ravel()
# Explain the difference between the two methods.

# Convert sales_data into a 1D array using flatten()
sales_flatten = sales_data.flatten()

print("Using flatten():")
print(sales_flatten)

# Convert sales_data into a 1D array using ravel()
sales_ravel = sales_data.ravel()

print("Using ravel():")
print(sales_ravel)

#  Difference between the two methods.                                                       |
# | ----------- | -------------------------------------------------------------- |
# | `flatten()` | Always creates a **copy** of the original array                |
# | `ravel()`   | Usually returns a **view** of the original array when possible |


Using flatten():
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]
Using ravel():
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


# --- Question 87: Reshape Sales Data ---

In [ ]:
# Reshape the 5 × 6 sales array into:

# 3 × 10
# 10 × 3
# 2 × 15
# 15 × 2
# Verify that no data is lost.

# Reshape into 3 × 10
sales_3x10 = sales_data.reshape(3, 10)

print("3 × 10:")
print(sales_3x10)


# Reshape into 10 × 3
sales_10x3 = sales_data.reshape(10, 3)

print("\n10 × 3:")
print(sales_10x3)


# Reshape into 2 × 15
sales_2x15 = sales_data.reshape(2, 15)

print("\n2 × 15:")
print(sales_2x15)


# Reshape into 15 × 2
sales_15x2 = sales_data.reshape(15, 2)

print("\n15 × 2:")
print(sales_15x2)

# Verify that no data is lost.

print("\n3 × 10:", np.array_equal(sales_data, sales_3x10.reshape(5, 6)))
print("10 × 3:", np.array_equal(sales_data, sales_10x3.reshape(5, 6)))
print("2 × 15:", np.array_equal(sales_data, sales_2x15.reshape(5, 6)))
print("15 × 2:", np.array_equal(sales_data, sales_15x2.reshape(5, 6)))

3 × 10:
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]

10 × 3:
[[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]

2 × 15:
[[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000  280000  225000  175000  205000]]

15 × 2:
[[ 850000  420000]
 [ 310000  275000]
 [ 190000  225000]
 [ 780000  460000]
 [ 295000  310000]
 [ 210000  240000]
 [ 920000  390000]
 [ 340000  260000]
 [ 185000  215000]
 [1050000  51000

# --- Question 88: Transpose Sales Data ---

In [ ]:
# Transpose the sales array so that:

# Rows represent product categories
# Columns represent stores
# Display the new shape.

# Transpose the sales array
transposed_sales = sales_data.T

print("Transposed Sales Data:")
print(transposed_sales)

# Display the new shape
print("\nNew Shape:", transposed_sales.shape)

Transposed Sales Data:
[[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]

New Shape: (6, 5)


# --- Question 89: Combined Sales and Cost Array ---

In [ ]:
# Stack sales_data and cost_data vertically.

# Display the resulting shape.

# Stack sales_data and cost_data vertically
combined_data = np.vstack((sales_data, cost_data))

print("Combined Data:")
print(combined_data)

# Display the resulting shape
print("\nResulting Shape:", combined_data.shape)

Combined Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]

Resulting Shape: (10, 6)


# --- Question 90: Store-Level Combined Data ---

In [ ]:
# Create a three-dimensional array where:

# First layer contains sales data
# Second layer contains cost data
# Use np.stack().

# Display the shape of the new array.

# Stack sales_data and cost_data into a 3D array
combined_3d = np.stack((sales_data, cost_data))

print("3D Array:")
print(combined_3d)

print("\nShape:", combined_3d.shape)

3D Array:
[[[ 850000  420000  310000  275000  190000  225000]
  [ 780000  460000  295000  310000  210000  240000]
  [ 920000  390000  340000  260000  185000  215000]
  [1050000  510000  375000  345000  250000  290000]
  [ 690000  405000  280000  225000  175000  205000]]

 [[ 640000  315000  220000  205000  125000  160000]
  [ 590000  350000  210000  225000  140000  170000]
  [ 700000  295000  245000  195000  120000  155000]
  [ 790000  390000  265000  250000  165000  205000]
  [ 530000  310000  205000  170000  115000  145000]]]

Shape: (2, 5, 6)


# === Part 16: Missing Data Scenario ===

In [ ]:
# The company discovers that some sales values were not recorded.

sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
])

# --- Question 91: Missing Value Detection ---

In [ ]:
# Find:

# Total number of missing values


total_missing = np.sum(np.isnan(sales_data))

print("Total Missing Values:", total_missing)



Total Missing Values: 0


In [ ]:
# Location of missing values

# Find row and column indexes of missing values
store_indexes, category_indexes = np.where(np.isnan(sales_data))

print("Store Indexes:", store_indexes)
print("Category Indexes:", category_indexes)

Store Indexes: []
Category Indexes: []


In [ ]:
# Stores and categories containing missing values

# Display stores and categories containing missing values
for store_index, category_index in zip(store_indexes, category_indexes):
    print(
        "Store:", stores[store_index],
        "| Category:", categories[category_index]
    )

# --- Question 92: Replace Missing Values with Zero ---

In [ ]:
# Replace all missing sales values with zero.

# Replace missing values with 0
sales_data = np.nan_to_num(sales_data, nan=0)

print("Updated Sales Data:")
print(sales_data)

Updated Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]


# --- Question 93: Replace with Company Average ---

In [ ]:
# Replace missing values with the overall average of available sales values.

# Use np.nanmean().

# Calculate the overall average of available sales values
average_sales = np.nanmean(sales_data)

# Replace missing values with the average
updated_sales_data = np.where(
    np.isnan(sales_data),
    average_sales,
    sales_data
)

print("Average Sales:", average_sales)
print("\nUpdated Sales Data:")
print(updated_sales_data)

Average Sales: 389166.6666666667

Updated Sales Data:
[[ 850000.  420000.  310000.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  310000.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  510000.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  175000.  205000.]]


# --- Question 94: Replace with Category Average ---

In [ ]:
# Replace each missing value with the average
     #  sales value of its respective product category.

# Calculate average sales for each category
category_average = np.nanmean(sales_data, axis=0)

# Find missing values
missing_mask = np.isnan(sales_data)

# Replace missing values with their respective category average
updated_sales_data = np.where(
    missing_mask,
    category_average,
    sales_data
)

print("Category Averages:")
print(category_average)

print("\nUpdated Sales Data:")
print(updated_sales_data)

Category Averages:
[858000. 437000. 320000. 283000. 202000. 235000.]

Updated Sales Data:
[[ 850000.  420000.  310000.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  310000.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  510000.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  175000.  205000.]]


# --- Question 95: Missing Value Impact ---

In [ ]:
# Compare total sales before and after replacing missing values with zero.

# Total sales before replacing missing values
total_before = np.nansum(sales_data)

# Replace missing values with zero
sales_with_zero = np.nan_to_num(sales_data, nan=0)

# Total sales after replacing missing values
total_after = np.sum(sales_with_zero)

# Display comparison
print("Total Sales Before:", total_before)
print("Total Sales After:", total_after)

Total Sales Before: 11675000
Total Sales After: 11675000


# === Part 17: Conditional Business Decisions ===

# --- Question 96: Store Performance Labels ---

In [ ]:
# Classify each store based on total sales:

# "Excellent": Total sales above ₹28,00,000
# "Good": Total sales between ₹24,00,000 and ₹28,00,000
# "Needs Improvement": Total sales below ₹24,00,000
# Use np.select().

# Calculate total sales for each store
store_total_sales = np.sum(sales_data, axis=1)

# Define conditions
conditions = [
    store_total_sales > 2800000,
    (store_total_sales >= 2400000) & (store_total_sales <= 2800000),
    store_total_sales < 2400000
]

# Define classifications
choices = [
    "Excellent",
    "Good",
    "Needs Improvement"
]

# Classify each store
store_classification = np.select(
    conditions,
    choices,
    default="Unknown"
)

# Display results
for store, total, classification in zip(
    stores, store_total_sales, store_classification
):
    print(store, "| Total Sales:", total, "|", classification)

Bengaluru | Total Sales: 2270000 | Needs Improvement
Hyderabad | Total Sales: 2295000 | Needs Improvement
Chennai | Total Sales: 2310000 | Needs Improvement
Mumbai | Total Sales: 2820000 | Excellent
Pune | Total Sales: 1980000 | Needs Improvement


# --- Question 97: Profitability Classification ---

In [ ]:
# Classify each store-category combination as:

# "Highly Profitable": Profit above ₹2,00,000
# "Profitable": Profit between ₹1,00,000 and ₹2,00,000
# "Low Profit": Profit below ₹1,00,000
# "Loss": Profit below zero

# Define conditions
conditions = [
    profit_data > 200000,
    (profit_data >= 100000) & (profit_data <= 200000),
    (profit_data >= 0) & (profit_data < 100000),
    profit_data < 0
]

# Define labels
choices = [
    "Highly Profitable",
    "Profitable",
    "Low Profit",
    "Loss"
]

# Classify every store-category combination
profit_classification = np.select(
    conditions,
    choices,
    default="Unknown"
)

print("Profit Classification:")
print(profit_classification)

Profit Classification:
[['Highly Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Profitable' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Highly Profitable' 'Profitable' 'Profitable' 'Low Profit' 'Low Profit'
  'Low Profit']
 ['Profitable' 'Low Profit' 'Low Profit' 'Low Profit' 'Low Profit'
  'Low Profit']]


# --- Question 98: Expansion Recommendation ---

In [ ]:
# A store is eligible for expansion when:

# Total sales are above ₹25,00,000
# Total profit is above ₹7,00,000
# Overall profit margin is above 25%
# Identify eligible stores.

# Calculate total sales for each store
store_total_sales = np.sum(sales_data, axis=1)

# Calculate total profit for each store
store_total_profit = np.sum(profit_data, axis=1)

# Calculate overall profit margin for each store
store_profit_margin = (
    store_total_profit / store_total_sales
) * 100

# Find eligible stores
eligible_mask = (
    (store_total_sales > 2500000) &
    (store_total_profit > 700000) &
    (store_profit_margin > 25)
)

# Display eligible stores
print("Eligible Stores for Expansion:")

for index in np.where(eligible_mask)[0]:
    print(
        "Store:", stores[index],
        "| Total Sales:", store_total_sales[index],
        "| Total Profit:", store_total_profit[index],
        "| Profit Margin:", round(store_profit_margin[index], 2), "%"
    )

Eligible Stores for Expansion:
Store: Mumbai | Total Sales: 2820000 | Total Profit: 755000 | Profit Margin: 26.77 %


# --- Question 99: Category Promotion Recommendation ---

In [ ]:
# A product category should receive additional promotion when:

# Average sales are below ₹3,00,000
# Profit margin is above 25%
# Identify the categories that satisfy these conditions.

# Calculate average sales for each category
category_average_sales = np.mean(sales_data, axis=0)

# Calculate total sales and total profit for each category
category_total_sales = np.sum(sales_data, axis=0)
category_total_profit = np.sum(profit_data, axis=0)

# Calculate profit margin for each category
category_profit_margin = (
    category_total_profit / category_total_sales
) * 100

# Find categories that need additional promotion
promotion_mask = (
    (category_average_sales < 300000) &
    (category_profit_margin > 25)
)

# Display eligible categories
print("Categories for Additional Promotion:")

for index in np.where(promotion_mask)[0]:
    print(
        "Category:", categories[index],
        "| Average Sales:", round(category_average_sales[index], 2),
        "| Profit Margin:", round(category_profit_margin[index], 2), "%"
    )

Categories for Additional Promotion:
Category: Furniture | Average Sales: 283000.0 | Profit Margin: 26.15 %
Category: Beauty | Average Sales: 202000.0 | Profit Margin: 34.16 %
Category: Sports | Average Sales: 235000.0 | Profit Margin: 28.94 %


# --- Question 100: Cost Optimization Recommendation ---

In [ ]:
# Find store-category combinations where:

# Cost is greater than ₹2,50,000
# Profit margin is below 25%
# These combinations should be reviewed for cost optimization.

# Calculate profit margin for every store-category combination
profit_margin = (profit_data / sales_data) * 100

# Find combinations that need cost optimization
cost_review_mask = (
    (cost_data > 250000) &
    (profit_margin < 25)
)

# Get store and category indexes
store_indexes, category_indexes = np.where(cost_review_mask)

# Display the combinations
print("Combinations for Cost Optimization:")

for store_index, category_index in zip(store_indexes, category_indexes):
    print(
        "Store:", stores[store_index],
        "| Category:", categories[category_index],
        "| Cost:", cost_data[store_index, category_index],
        "| Profit Margin:", round(profit_margin[store_index, category_index], 2), "%"
    )

Combinations for Cost Optimization:
Store: Bengaluru | Category: Electronics | Cost: 640000 | Profit Margin: 24.71 %
Store: Hyderabad | Category: Electronics | Cost: 590000 | Profit Margin: 24.36 %
Store: Hyderabad | Category: Groceries | Cost: 350000 | Profit Margin: 23.91 %
Store: Chennai | Category: Electronics | Cost: 700000 | Profit Margin: 23.91 %
Store: Chennai | Category: Groceries | Cost: 295000 | Profit Margin: 24.36 %
Store: Mumbai | Category: Electronics | Cost: 790000 | Profit Margin: 24.76 %
Store: Mumbai | Category: Groceries | Cost: 390000 | Profit Margin: 23.53 %
Store: Pune | Category: Electronics | Cost: 530000 | Profit Margin: 23.19 %
Store: Pune | Category: Groceries | Cost: 310000 | Profit Margin: 23.46 %


# === Part 18: Inventory Scenario ===

Use the following inventory arrays:

In [ ]:
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

# --- Question 101: Closing Stock ---

In [ ]:
# Calculate closing stock using:

# Closing Stock = Opening Stock - Units Sold

# Calculate closing stock
closing_stock = opening_stock - units_sold

print("Closing Stock:")
print(closing_stock)

Closing Stock:
[[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


# --- Question 102: Low-Stock Identification ---

In [ ]:
# Identify store-category combinations where closing stock is below 30 units.

# Find combinations where closing stock is below 30 units
store_indexes, category_indexes = np.where(closing_stock < 30)

# Display the affected stores and categories
print("Low Closing Stock Combinations:")

for store_index, category_index in zip(store_indexes, category_indexes):
    print(
        "Store:", stores[store_index],
        "| Category:", categories[category_index],
        "| Closing Stock:", closing_stock[store_index, category_index]
    )

Low Closing Stock Combinations:
Store: Bengaluru | Category: Electronics | Closing Stock: 25
Store: Bengaluru | Category: Furniture | Closing Stock: 25
Store: Hyderabad | Category: Electronics | Closing Stock: 25
Store: Hyderabad | Category: Furniture | Closing Stock: 25
Store: Chennai | Category: Electronics | Closing Stock: 25
Store: Chennai | Category: Furniture | Closing Stock: 25
Store: Mumbai | Category: Electronics | Closing Stock: 25
Store: Pune | Category: Electronics | Closing Stock: 25
Store: Pune | Category: Furniture | Closing Stock: 20


# --- Question 103: Stock Availability Percentage ---

In [ ]:
# Calculate the percentage of opening stock that remains unsold.

# Calculate percentage of opening stock remaining unsold
percentage_remaining = (closing_stock / opening_stock) * 100

# Round to 2 decimal places
percentage_remaining = np.round(percentage_remaining, 2)

print("Percentage of Opening Stock Remaining:")
print(percentage_remaining)

Percentage of Opening Stock Remaining:
[[20.83 15.56 20.   27.78 24.   22.22]
 [22.73 16.   17.86 25.   22.22 22.5 ]
 [19.23 16.67 15.62 29.41 25.   23.53]
 [16.67 14.55 15.71 25.   21.67 20.45]
 [25.   17.5  21.15 26.67 25.   25.  ]]


# --- Question 104: Fast-Moving Products ---

In [ ]:
# A product is considered fast-moving when more than 80% of its opening stock has been sold.

# Identify fast-moving store-category combinations.

# Calculate percentage of opening stock sold
percentage_sold = (units_sold / opening_stock) * 100

# Find fast-moving combinations
fast_moving_mask = percentage_sold > 80

# Get store and category indexes
store_indexes, category_indexes = np.where(fast_moving_mask)

# Display fast-moving combinations
print("Fast-Moving Products:")

for store_index, category_index in zip(store_indexes, category_indexes):
    print(
        "Store:", stores[store_index],
        "| Category:", categories[category_index],
        "| Percentage Sold:", round(
            percentage_sold[store_index, category_index], 2
        ), "%"
    )

Fast-Moving Products:
Store: Bengaluru | Category: Groceries | Percentage Sold: 84.44 %
Store: Hyderabad | Category: Groceries | Percentage Sold: 84.0 %
Store: Hyderabad | Category: Clothing | Percentage Sold: 82.14 %
Store: Chennai | Category: Electronics | Percentage Sold: 80.77 %
Store: Chennai | Category: Groceries | Percentage Sold: 83.33 %
Store: Chennai | Category: Clothing | Percentage Sold: 84.38 %
Store: Mumbai | Category: Electronics | Percentage Sold: 83.33 %
Store: Mumbai | Category: Groceries | Percentage Sold: 85.45 %
Store: Mumbai | Category: Clothing | Percentage Sold: 84.29 %
Store: Pune | Category: Groceries | Percentage Sold: 82.5 %


# --- Question 105: Category-Wise Units Sold ---

In [ ]:
# Calculate the total units sold for each product category.

# Calculate total units sold for each product category
category_units_sold = np.sum(units_sold, axis=0)

# Display category names with total units sold
for category, total in zip(categories, category_units_sold):
    print(category + ":", total)

Electronics: 485
Groceries: 1950
Clothing: 1240
Furniture: 345
Beauty: 980
Sports: 720


# --- Question 106: Store-Wise Units Sold ---

In [ ]:
# Calculate total units sold by each store.

# Calculate total units sold by each store
store_units_sold = np.sum(units_sold, axis=1)

# Display store names with total units sold
for store, total in zip(stores, store_units_sold):
    print(store + ":", total)

Bengaluru: 1110
Hyderabad: 1175
Chennai: 1095
Mumbai: 1390
Pune: 950


# --- Question 107: Best Store by Unit Sales ---

In [ ]:
# Identify the store that sold the highest total number of units.

# Find the index of the store with the highest units sold
highest_units_index = np.argmax(store_units_sold)

# Get the store name
highest_units_store = stores[highest_units_index]

# Get the total units sold
highest_units = store_units_sold[highest_units_index]

print("Store with Highest Units Sold:", highest_units_store)
print("Total Units Sold:", highest_units)

Store with Highest Units Sold: Mumbai
Total Units Sold: 1390


# --- Question 108: Reorder Requirement ---

In [ ]:
# A store should reorder a category when closing stock is below 25 units.

# Create a Boolean reorder matrix.

# Create Boolean reorder matrix
reorder_matrix = closing_stock < 25

print("Reorder Matrix:")
print(reorder_matrix)

Reorder Matrix:
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


# --- Question 109: Reorder Quantity ---

In [ ]:
# Assume each category must maintain 100 units after reordering.

# Calculate reorder quantities only for combinations where closing stock is below 25.

# For all other combinations, return zero.

# Calculate reorder quantities
reorder_quantity = np.where(
    closing_stock < 25,
    100 - closing_stock,
    0
)

print("Reorder Quantity:")
print(reorder_quantity)

Reorder Quantity:
[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


# === Part 19: Advanced NumPy Questions ===

# --- Question 110: Cumulative Store Sales ---

In [ ]:
# Calculate cumulative category sales for each store using np.cumsum().

# Calculate cumulative category sales for each store
cumulative_sales = np.cumsum(sales_data, axis=1)

print("Cumulative Sales:")
print(cumulative_sales)

Cumulative Sales:
[[ 850000 1270000 1580000 1855000 2045000 2270000]
 [ 780000 1240000 1535000 1845000 2055000 2295000]
 [ 920000 1310000 1650000 1910000 2095000 2310000]
 [1050000 1560000 1935000 2280000 2530000 2820000]
 [ 690000 1095000 1375000 1600000 1775000 1980000]]


# --- Question 111: Cumulative Company Sales ---

In [ ]:
# Flatten the sales array and calculate cumulative company sales.

# Flatten the sales array
flattened_sales = sales_data.flatten()

# Calculate cumulative company sales
cumulative_company_sales = np.cumsum(flattened_sales)

print("Flattened Sales:")
print(flattened_sales)

print("\nCumulative Company Sales:")
print(cumulative_company_sales)

Flattened Sales:
[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]

Cumulative Company Sales:
[  850000  1270000  1580000  1855000  2045000  2270000  3050000  3510000
  3805000  4115000  4325000  4565000  5485000  5875000  6215000  6475000
  6660000  6875000  7925000  8435000  8810000  9155000  9405000  9695000
 10385000 10790000 11070000 11295000 11470000 11675000]


# --- Question 112: Sales Difference Between Categories ---

In [ ]:
# Calculate the difference between consecutive category sales for each store using np.diff().

# Calculate difference between consecutive category sales
sales_difference = np.diff(sales_data, axis=1)

print("Difference Between Consecutive Category Sales:")
print(sales_difference)

Difference Between Consecutive Category Sales:
[[-430000 -110000  -35000  -85000   35000]
 [-320000 -165000   15000 -100000   30000]
 [-530000  -50000  -80000  -75000   30000]
 [-540000 -135000  -30000  -95000   40000]
 [-285000 -125000  -55000  -50000   30000]]


# --- Question 113: Unique Sales Values ---

In [ ]:
# Find all unique sales values in sales_data.

# Also count the frequency of each value.

# Find unique sales values and their frequencies
unique_sales, frequency = np.unique(
    sales_data,
    return_counts=True
)

# Display values and frequencies
for value, count in zip(unique_sales, frequency):
    print("Sales Value:", value, "| Frequency:", count)

Sales Value: 175000 | Frequency: 1
Sales Value: 185000 | Frequency: 1
Sales Value: 190000 | Frequency: 1
Sales Value: 205000 | Frequency: 1
Sales Value: 210000 | Frequency: 1
Sales Value: 215000 | Frequency: 1
Sales Value: 225000 | Frequency: 2
Sales Value: 240000 | Frequency: 1
Sales Value: 250000 | Frequency: 1
Sales Value: 260000 | Frequency: 1
Sales Value: 275000 | Frequency: 1
Sales Value: 280000 | Frequency: 1
Sales Value: 290000 | Frequency: 1
Sales Value: 295000 | Frequency: 1
Sales Value: 310000 | Frequency: 2
Sales Value: 340000 | Frequency: 1
Sales Value: 345000 | Frequency: 1
Sales Value: 375000 | Frequency: 1
Sales Value: 390000 | Frequency: 1
Sales Value: 405000 | Frequency: 1
Sales Value: 420000 | Frequency: 1
Sales Value: 460000 | Frequency: 1
Sales Value: 510000 | Frequency: 1
Sales Value: 690000 | Frequency: 1
Sales Value: 780000 | Frequency: 1
Sales Value: 850000 | Frequency: 1
Sales Value: 920000 | Frequency: 1
Sales Value: 1050000 | Frequency: 1


# --- Question 114: Search for Specific Sales ---

In [ ]:
# Check whether the value ₹4,20,000 exists in the sales array.

# Return its location.

# Check whether 420000 exists and find its location
store_indexes, category_indexes = np.where(sales_data == 420000)

if len(store_indexes) > 0:
    print("Value exists")

    for store_index, category_index in zip(store_indexes, category_indexes):
        print(
            "Store:", stores[store_index],
            "| Category:", categories[category_index]
        )
else:
    print("Value does not exist")

Value exists
Store: Bengaluru | Category: Groceries


# --- Question 115: Compare Sales and Cost ---

In [ ]:
# Create a Boolean array showing whether sales are greater than cost for every combination.

# Verify whether all combinations are profitable using np.all().

# Create a Boolean array for sales greater than cost
profitable = sales_data > cost_data

print("Profitability Matrix:")
print(profitable)

# Check whether all store-category combinations are profitable
all_profitable = np.all(profitable)

print("\nAre all combinations profitable?", all_profitable)

Profitability Matrix:
[[ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]]

Are all combinations profitable? True


# --- Question 116: Clip Profit Values ---

In [ ]:
# For reporting purposes, management wants profit values limited to:

# Minimum: ₹75,000
# Maximum: ₹2,50,000
# Use np.clip() to create a reporting profit array.

# Create reporting profit array with limits
reporting_profit = np.clip(
    profit_data,
    75000,
    250000
)

print("Reporting Profit Array:")
print(reporting_profit)

Reporting Profit Array:
[[210000 105000  90000  75000  75000  75000]
 [190000 110000  85000  85000  75000  75000]
 [220000  95000  95000  75000  75000  75000]
 [250000 120000 110000  95000  85000  85000]
 [160000  95000  75000  75000  75000  75000]]


# --- Question 117: Normalize Sales Data ---

In [ ]:
# Normalize all sales values using min-max normalization:

# Normalized Sales =
# (Sales - Minimum Sales) / (Maximum Sales - Minimum Sales)

# Find minimum and maximum sales values
min_sales = np.min(sales_data)
max_sales = np.max(sales_data)

# Normalize sales values
normalized_sales = (
    (sales_data - min_sales) /
    (max_sales - min_sales)
)

print("Normalized Sales:")
print(normalized_sales)

Normalized Sales:
[[0.77142857 0.28       0.15428571 0.11428571 0.01714286 0.05714286]
 [0.69142857 0.32571429 0.13714286 0.15428571 0.04       0.07428571]
 [0.85142857 0.24571429 0.18857143 0.09714286 0.01142857 0.04571429]
 [1.         0.38285714 0.22857143 0.19428571 0.08571429 0.13142857]
 [0.58857143 0.26285714 0.12       0.05714286 0.         0.03428571]]


# --- Question 118: Standardize Sales Data ---

In [ ]:
# Standardize sales using:

# Standardized Sales =
# (Sales - Mean Sales) / Standard Deviation

# Calculate mean and standard deviation
mean_sales = np.mean(sales_data)
std_sales = np.std(sales_data)

# Standardize sales data
standardized_sales = (
    (sales_data - mean_sales) / std_sales
)

print("Mean Sales:", mean_sales)
print("Standard Deviation:", std_sales)

print("\nStandardized Sales:")
print(standardized_sales)

Mean Sales: 389166.6666666667
Standard Deviation: 230322.53954448793

Standardized Sales:
[[ 2.00081735  0.13387024 -0.34372088 -0.49568169 -0.86472938 -0.71276857]
 [ 1.69689573  0.30753974 -0.40884695 -0.34372088 -0.77789463 -0.64764251]
 [ 2.30473897  0.00361811 -0.21346876 -0.56080776 -0.88643807 -0.75618594]
 [ 2.86916484  0.52462661 -0.06150795 -0.19176007 -0.60422513 -0.43055563]
 [ 1.30613936  0.06874418 -0.47397301 -0.71276857 -0.92985544 -0.79960332]]


# --- Question 119: Round Values ---

In [ ]:
# Convert profit margin values into:

# Two decimal places
# Nearest whole number
# Floor values
# Ceiling values

# Profit margin rounded to 2 decimal places
profit_margin_2_decimals = np.round(profit_margin, 2)

# Profit margin rounded to nearest whole number
profit_margin_nearest = np.round(profit_margin)

# Floor values
profit_margin_floor = np.floor(profit_margin)

# Ceiling values
profit_margin_ceil = np.ceil(profit_margin)

# Display results
print("Profit Margin - 2 Decimal Places:")
print(profit_margin_2_decimals)

print("\nProfit Margin - Nearest Whole Number:")
print(profit_margin_nearest)

print("\nProfit Margin - Floor Values:")
print(profit_margin_floor)

print("\nProfit Margin - Ceiling Values:")
print(profit_margin_ceil)

Profit Margin - 2 Decimal Places:
[[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]

Profit Margin - Nearest Whole Number:
[[25. 25. 29. 25. 34. 29.]
 [24. 24. 29. 27. 33. 29.]
 [24. 24. 28. 25. 35. 28.]
 [25. 24. 29. 28. 34. 29.]
 [23. 23. 27. 24. 34. 29.]]

Profit Margin - Floor Values:
[[24. 25. 29. 25. 34. 28.]
 [24. 23. 28. 27. 33. 29.]
 [23. 24. 27. 25. 35. 27.]
 [24. 23. 29. 27. 34. 29.]
 [23. 23. 26. 24. 34. 29.]]

Profit Margin - Ceiling Values:
[[25. 25. 30. 26. 35. 29.]
 [25. 24. 29. 28. 34. 30.]
 [24. 25. 28. 25. 36. 28.]
 [25. 24. 30. 28. 34. 30.]
 [24. 24. 27. 25. 35. 30.]]


# --- Question 120: Save and Load Data ---

In [ ]:
# Save the following arrays as NumPy binary files:

# sales_data.npy
# cost_data.npy
# profit_data.npy
# Load them back and verify that the loaded arrays are equal to the original arrays.

# Save arrays as NumPy binary files
np.save("sales_data.npy", sales_data)
np.save("cost_data.npy", cost_data)
np.save("profit_data.npy", profit_data)

print("Arrays saved successfully!")

# Load the saved arrays
loaded_sales_data = np.load("sales_data.npy")
loaded_cost_data = np.load("cost_data.npy")
loaded_profit_data = np.load("profit_data.npy")

print("Arrays loaded successfully!")

print("Sales Data Equal:",
      np.array_equal(sales_data, loaded_sales_data))

print("Cost Data Equal:",
      np.array_equal(cost_data, loaded_cost_data))

print("Profit Data Equal:",
      np.array_equal(profit_data, loaded_profit_data))

Arrays saved successfully!
Arrays loaded successfully!
Sales Data Equal: True
Cost Data Equal: True
Profit Data Equal: True


# === Part 20: Final Retail Analytics Project ===

Prepare a complete NumPy-based retail performance report.

Your report must contain the following information:

Company Summary

Total company sales

Total company cost

Total company profit

Overall company profit margin

Average transaction value

Highest individual sales value

Lowest individual sales value

In [ ]:
# Make sure profit_data exists
profit_data = sales_data - cost_data

# 1. Total company sales
total_company_sales = np.sum(sales_data)

# 2. Total company cost
total_company_cost = np.sum(cost_data)

# 3. Total company profit
total_company_profit = np.sum(profit_data)

# 4. Overall company profit margin
overall_profit_margin = (
    total_company_profit / total_company_sales
) * 100

# 5. Average transaction value
average_transaction_value = np.mean(sales_data)

# 6. Highest individual sales value
highest_sales = np.max(sales_data)

# 7. Lowest individual sales value
lowest_sales = np.min(sales_data)

# Display Company Summary
print("----- COMPANY SUMMARY -----")

print("1. Total Company Sales:", total_company_sales)
print("2. Total Company Cost:", total_company_cost)
print("3. Total Company Profit:", total_company_profit)
print("4. Overall Profit Margin:", round(overall_profit_margin, 2), "%")
print("5. Average Transaction Value:", round(average_transaction_value, 2))
print("6. Highest Individual Sales:", highest_sales)
print("7. Lowest Individual Sales:", lowest_sales)

----- COMPANY SUMMARY -----
1. Total Company Sales: 11675000
2. Total Company Cost: 8600000
3. Total Company Profit: 3075000
4. Overall Profit Margin: 26.34 %
5. Average Transaction Value: 389166.67
6. Highest Individual Sales: 1050000
7. Lowest Individual Sales: 175000


Store Summary

For every store, display:

Total sales

Total cost

Total profit

Profit margin

Number of category targets achieved

Total units sold

Expansion eligibility

In [ ]:
# Calculate profit data
profit_data = sales_data - cost_data

# 1. Total sales for each store
store_total_sales = np.sum(sales_data, axis=1)

# 2. Total cost for each store
store_total_cost = np.sum(cost_data, axis=1)

# 3. Total profit for each store
store_total_profit = np.sum(profit_data, axis=1)

# 4. Profit margin for each store
store_profit_margin = (
    store_total_profit / store_total_sales
) * 100

# 5. Number of category targets achieved
target_achieved = sales_data >= sales_targets
categories_achieved = np.sum(target_achieved, axis=1)

# 6. Total units sold by each store
store_units_sold = np.sum(units_sold, axis=1)

# 7. Expansion eligibility
expansion_eligible = (
    (store_total_sales > 2500000) &
    (store_total_profit > 700000) &
    (store_profit_margin > 25)
)

# Display Store Summary
print("---------- STORE SUMMARY ----------\n")

for i in range(len(stores)):
    print("Store:", stores[i])
    print("Total Sales:", store_total_sales[i])
    print("Total Cost:", store_total_cost[i])
    print("Total Profit:", store_total_profit[i])
    print("Profit Margin:", round(store_profit_margin[i], 2), "%")
    print("Category Targets Achieved:", categories_achieved[i])
    print("Total Units Sold:", store_units_sold[i])
    print("Expansion Eligible:", expansion_eligible[i])
    print("-" * 35)

---------- STORE SUMMARY ----------

Store: Bengaluru
Total Sales: 2270000
Total Cost: 1665000
Total Profit: 605000
Profit Margin: 26.65 %
Category Targets Achieved: 3
Total Units Sold: 1110
Expansion Eligible: False
-----------------------------------
Store: Hyderabad
Total Sales: 2295000
Total Cost: 1685000
Total Profit: 610000
Profit Margin: 26.58 %
Category Targets Achieved: 4
Total Units Sold: 1175
Expansion Eligible: False
-----------------------------------
Store: Chennai
Total Sales: 2310000
Total Cost: 1710000
Total Profit: 600000
Profit Margin: 25.97 %
Category Targets Achieved: 2
Total Units Sold: 1095
Expansion Eligible: False
-----------------------------------
Store: Mumbai
Total Sales: 2820000
Total Cost: 2065000
Total Profit: 755000
Profit Margin: 26.77 %
Category Targets Achieved: 6
Total Units Sold: 1390
Expansion Eligible: True
-----------------------------------
Store: Pune
Total Sales: 1980000
Total Cost: 1475000
Total Profit: 505000
Profit Margin: 25.51 %
Category

Category Summary

For every category, display:

Total sales

Total cost

Total profit

Profit margin

Average sales

Number of stores achieving the target

Total units sold

In [ ]:
# Calculate profit data
profit_data = sales_data - cost_data

# 1. Total sales for each category
category_total_sales = np.sum(sales_data, axis=0)

# 2. Total cost for each category
category_total_cost = np.sum(cost_data, axis=0)

# 3. Total profit for each category
category_total_profit = np.sum(profit_data, axis=0)

# 4. Profit margin for each category
category_profit_margin = (
    category_total_profit / category_total_sales
) * 100

# 5. Average sales for each category
category_average_sales = np.mean(sales_data, axis=0)

# 6. Number of stores achieving the target
target_achieved = sales_data >= sales_targets
stores_achieved_target = np.sum(target_achieved, axis=0)

# 7. Total units sold for each category
category_units_sold = np.sum(units_sold, axis=0)

# Display Category Summary
print("---------- CATEGORY SUMMARY ----------\n")

for i in range(len(categories)):
    print("Category:", categories[i])
    print("Total Sales:", category_total_sales[i])
    print("Total Cost:", category_total_cost[i])
    print("Total Profit:", category_total_profit[i])
    print("Profit Margin:", round(category_profit_margin[i], 2), "%")
    print("Average Sales:", round(category_average_sales[i], 2))
    print("Stores Achieving Target:", stores_achieved_target[i])
    print("Total Units Sold:", category_units_sold[i])
    print("-" * 40)

---------- CATEGORY SUMMARY ----------

Category: Electronics
Total Sales: 4290000
Total Cost: 3250000
Total Profit: 1040000
Profit Margin: 24.24 %
Average Sales: 858000.0
Stores Achieving Target: 3
Total Units Sold: 485
----------------------------------------
Category: Groceries
Total Sales: 2185000
Total Cost: 1660000
Total Profit: 525000
Profit Margin: 24.03 %
Average Sales: 437000.0
Stores Achieving Target: 2
Total Units Sold: 1950
----------------------------------------
Category: Clothing
Total Sales: 1600000
Total Cost: 1145000
Total Profit: 455000
Profit Margin: 28.44 %
Average Sales: 320000.0
Stores Achieving Target: 3
Total Units Sold: 1240
----------------------------------------
Category: Furniture
Total Sales: 1415000
Total Cost: 1045000
Total Profit: 370000
Profit Margin: 26.15 %
Average Sales: 283000.0
Stores Achieving Target: 2
Total Units Sold: 345
----------------------------------------
Category: Beauty
Total Sales: 1010000
Total Cost: 665000
Total Profit: 345000
Pr

Management Recommendations

Based on the analysis, identify:

Best-performing store

Lowest-performing store

Most profitable category

Lowest-profit category

Store recommended for expansion

Category requiring additional marketing

Store-category combinations needing cost optimization

Store-category combinations requiring inventory reorder

In [ ]:
# ==========================================
# MANAGEMENT RECOMMENDATIONS
# ==========================================

# Make sure profit data exists
profit_data = sales_data - cost_data

# ------------------------------------------
# 1. Best-performing store
# Based on highest total profit
# ------------------------------------------
store_total_sales = np.sum(sales_data, axis=1)
store_total_profit = np.sum(profit_data, axis=1)

best_store_index = np.argmax(store_total_profit)

print("1. Best-Performing Store:")
print(stores[best_store_index])


# ------------------------------------------
# 2. Lowest-performing store
# Based on lowest total profit
# ------------------------------------------
lowest_store_index = np.argmin(store_total_profit)

print("\n2. Lowest-Performing Store:")
print(stores[lowest_store_index])


# ------------------------------------------
# 3. Most profitable category
# ------------------------------------------
category_total_profit = np.sum(profit_data, axis=0)

most_profitable_index = np.argmax(category_total_profit)

print("\n3. Most Profitable Category:")
print(categories[most_profitable_index])


# ------------------------------------------
# 4. Lowest-profit category
# ------------------------------------------
lowest_profit_category_index = np.argmin(category_total_profit)

print("\n4. Lowest-Profit Category:")
print(categories[lowest_profit_category_index])


# ------------------------------------------
# 5. Store recommended for expansion
# ------------------------------------------
store_profit_margin = (
    store_total_profit / store_total_sales
) * 100

expansion_mask = (
    (store_total_sales > 2500000) &
    (store_total_profit > 700000) &
    (store_profit_margin > 25)
)

print("\n5. Store Recommended for Expansion:")

for index in np.where(expansion_mask)[0]:
    print(stores[index])


# ------------------------------------------
# 6. Category requiring additional marketing
# ------------------------------------------
category_average_sales = np.mean(sales_data, axis=0)

category_total_sales = np.sum(sales_data, axis=0)

category_profit_margin = (
    category_total_profit / category_total_sales
) * 100

promotion_mask = (
    (category_average_sales < 300000) &
    (category_profit_margin > 25)
)

print("\n6. Categories Requiring Additional Marketing:")

for index in np.where(promotion_mask)[0]:
    print(categories[index])


# ------------------------------------------
# 7. Store-category combinations
# needing cost optimization
# ------------------------------------------
profit_margin = (profit_data / sales_data) * 100

cost_review_mask = (
    (cost_data > 250000) &
    (profit_margin < 25)
)

store_indexes, category_indexes = np.where(cost_review_mask)

print("\n7. Combinations Needing Cost Optimization:")

for store_index, category_index in zip(
    store_indexes, category_indexes
):
    print(
        stores[store_index],
        "-",
        categories[category_index]
    )


# ------------------------------------------
# 8. Store-category combinations
# requiring inventory reorder
# ------------------------------------------
reorder_mask = closing_stock < 25

store_indexes, category_indexes = np.where(reorder_mask)

print("\n8. Combinations Requiring Inventory Reorder:")

for store_index, category_index in zip(
    store_indexes, category_indexes
):
    print(
        stores[store_index],
        "-",
        categories[category_index]
    )

1. Best-Performing Store:
Mumbai

2. Lowest-Performing Store:
Pune

3. Most Profitable Category:
Electronics

4. Lowest-Profit Category:
Sports

5. Store Recommended for Expansion:
Mumbai

6. Categories Requiring Additional Marketing:
Furniture
Beauty
Sports

7. Combinations Needing Cost Optimization:
Bengaluru - Electronics
Hyderabad - Electronics
Hyderabad - Groceries
Chennai - Electronics
Chennai - Groceries
Mumbai - Electronics
Mumbai - Groceries
Pune - Electronics
Pune - Groceries

8. Combinations Requiring Inventory Reorder:
Pune - Furniture
